# Generated by Django 4.1.13 on 2024-08-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_tipo",
                    models.IntegerField(
                        choices=[(1, "Interno"), (2, "Externo"), (3, "Tercero")]
                    ),
                ),
                ("nombre", models.CharField(default="", max_length=50)),
                ("direccion", models.CharField(default="", max_length=100)),
                (
                    "tarifa",
                    models.DecimalField(decimal_places=2, max_digits=3, max_length=3),
                ),
                ("nota", models.TextField()),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
    ]
