# Generated by Django 4.1.13 on 2024-08-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Operacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_tipo_operacion",
                    models.CharField(
                        choices=[("terceros", "terceros"), ("interna", "interna")],
                        default="interna",
                        max_length=20,
                    ),
                ),
                ("status", models.TextField()),
                ("direccion_inicio", models.TextField()),
                ("direccion_final", models.TextField()),
                (
                    "tarifa",
                    models.DecimalField(decimal_places=2, max_digits=3, max_length=3),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_final", models.DateField()),
                ("cantidad", models.IntegerField()),
                ("comentario", models.TextField()),
                (
                    "precio",
                    models.DecimalField(decimal_places=2, max_digits=3, max_length=3),
                ),
            ],
            options={
                "ordering": ["status"],
            },
        ),
    ]
